language: python
python:
  - "3.6"
addons:
  postgresql: "9.4"
services:
  - postgresql
install:
  - "pip install -e ."
  - "pip install -r requirements-dev.txt"
script:
  - flake8
  - py.test
  - black --check .
  - createdb seed_identity_store
  - python manage.py makemigrations --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)
deploy:
  provider: pypi
  user: praekelt.org
  password:
    secure: HnjuxnCwoMnOsPainYsTSTsgWflI8v2zCjqZls8MGcyrri9FFUecJubsJ0Kh/6rB11mR42fTUENsD0dY+rgKR6QdmWKMrJPYk4BeDvsrf7EihVP91k0MFAQYUD4GEqBrZsBfdS4VPqfwv9vC0rdnP0OXiM44SWcbWDv9NW+7woqnE6JUgxl7R/4/QeOt0YgctaPU4tCzroL07u9pYxdy0rFm+yWcjZDKuJ92jj0snrWJJgx9a3L09NP6G+TpMdXnXud8PFYgnPiDyDBNvn4tuNPY4CCpqZy//4IMruZtnaDU1aAxOus5I08qFkQYCMnXadPSWeAeTDBDRAa8sZ98TlJxiwe1LCF2dGDiLoxfYphYQWXgkFbwWoBVjZYihz7LJ9XQ02Fgmc64Zj8yn3C4iSbVKV85e487Jy1l5P+IfJFL/7xx9jHKnKv+6AJ85M7oiGPyWpuLCuWQgxZF2srX26JL2tlsi94SWE8TBjIRj7uctKMKASDcIzy3waFzHDcNiiFT9R8wmdlywOyoTVw7Wky/TS7g0K01Wl3VgDpYGabTCNDdlh6+W97SgBU/n+uFGQPVijaxrKcoyx+ByDLthWlQcGCPUCnQ9JDgCmWv/ZALPpFhWMvLMzK2AdL9okdLvYH3ApibBnhJ6T25SDI373JtSsB6/QacoRhSODPtGAA=
  distributions: sdist bdist_wheel
  on:
    tags: true
