# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 12:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('identities', '0002_auto_20160204_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text=b'UUID this optout request.', primary_key=True, serialize=False)),
                ('address_type', models.CharField(default=b'', help_text=b'Address type used to identify the identity.', max_length=50)),
                ('address', models.CharField(default=b'', help_text=b'Address used to identify the identity.', max_length=255)),
                ('request_source', models.CharField(help_text=b'Service that the optout was requested from.', max_length=100)),
                ('requestor_source_id', models.CharField(help_text=b'ID for the user requesting the optout on the service that        it was requested from.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Time request was received.')),
                ('created_by', models.ForeignKey(help_text=b'User creating the OptOut', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optout_created', to=settings.AUTH_USER_MODEL)),
                ('identity', models.ForeignKey(help_text=b'UUID for the identity opting out.', null=True, on_delete=django.db.models.deletion.CASCADE, to='identities.Identity')),
            ],
        ),
    ]
