# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-18 07:53
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0005_optin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identities_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='identity',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'addresses': {}, 'default_addr_type': None}),
        ),
        migrations.AlterField(
            model_name='identity',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identities_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
